dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.12.4
git:
  depth: 1
script:
- make test
- make vet
- make build
- make release
branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
env:
  global:
  - secure: vpGQJhArbIL1OqPW1YGyqbS2zNGW0UqsXdBkcz0NnaDit0ABf9WM+naQsQmbw2gwhqWyZN6uKkVcDts4+9RJNt/nUqXpgv348o+19aKBDp0PTQ6UpIflvqQBfpoNw9IDRW169XY15+bPxeVkSQOMC4X7qvbiSBA+7L5e3WeZIvPldIItNhCG+1wkAOhJE2lNz8pxosx/DeZB+NR3shM7yA6aBAASISZNYedCwaNgkijHxeazPZUE8zAaanahEPUcA+6BB1Njb0OnCRagWAXfhV0O/Pceg1OlTpiNE7mW0MOken8Qi3sTuG7SFVRiBW6bwddOj7ScGxeTy8sgn+keP7wBpR7S0zhtKVYwNr21La69i1/9uI526eSheE2u4XBx8QZcfxpITGMc1/7aT+ph+wwdZmF/yxd9Mav3rS0VpxM0NBZ01vzdHTBSPCFonwuSAiSziouMME94Fmh4ur4no/ve5E6TI4glUNhWY58oCYLiUls1YVF0WV7NFko+FKCRP56TzK/CjVdAwJb6/pUXzKnct7oFcdRj3ceH/HuqQ6IdlFVwOeobiX2IgS+LO5G5PC9XkAN1a4+tZDf64jjhD3HLfg6RbFPCpOr+PZ/LeT1im+DEIdAYbx400gy3IUZe8iPLqsfdcM/sbrKxVFmOvt/n6AVQPevoVn6Kx5h+Lqg=
